name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Publish
        run: dotnet publish -c Release --self-contained false --output "Publish"
        
      - name: Publish SC
        run: dotnet publish -c Release --self-contained true --output "PublishSC"
        
      - name: Test
        run: dotnet test -c Release --no-restore --no-build --verbosity normal

      - name: Upload publish results
        uses: actions/upload-artifact@v2
        with:
          name: PopIt.exe
          path: Publish/PopIt.exe

      - name: Upload publish sc results
        uses: actions/upload-artifact@v2
        with:
          name: PopIt-SC.exe
          path: PublishSC/PopIt.exe
    
        if: ${{ always() }}
